language: go

services:
  - postgresql

go:
  - 1.13.6
  - master

sudo: false

script:
  - go test ./... -v -race -covermode=atomic -coverprofile=coverage.txt -coverpkg=./...

after_success:
- bash <(curl -s https://codecov.io/bash)