// Code generated by MockGen. DO NOT EDIT.
// Source: helper/i18n//i18n.go

// Package mock_helper is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	i18n "github.com/nicksnyder/go-i18n/v2/i18n"
)

// MockI18nHelper is a mock of I18nHelper interface.
type MockI18nHelper struct {
	ctrl     *gomock.Controller
	recorder *MockI18nHelperMockRecorder
}

// MockI18nHelperMockRecorder is the mock recorder for MockI18nHelper.
type MockI18nHelperMockRecorder struct {
	mock *MockI18nHelper
}

// NewMockI18nHelper creates a new mock instance.
func NewMockI18nHelper(ctrl *gomock.Controller) *MockI18nHelper {
	mock := &MockI18nHelper{ctrl: ctrl}
	mock.recorder = &MockI18nHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI18nHelper) EXPECT() *MockI18nHelperMockRecorder {
	return m.recorder
}

// MustGetLocalizer mocks base method.
func (m *MockI18nHelper) MustGetLocalizer(chatID int64) *i18n.Localizer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustGetLocalizer", chatID)
	ret0, _ := ret[0].(*i18n.Localizer)
	return ret0
}

// MustGetLocalizer indicates an expected call of MustGetLocalizer.
func (mr *MockI18nHelperMockRecorder) MustGetLocalizer(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetLocalizer", reflect.TypeOf((*MockI18nHelper)(nil).MustGetLocalizer), chatID)
}
